### PR TITLE
Allow environment variables in threshold fields

### PR DESCRIPTION
**Pull request by pmv**

### CODE REVIEW

**Comment by pmv** [comment]
Any more changes needed before this can be reviewed?  Thanks!

**Comment by centic9** [comment]
sorry, just two half-contributors with limited free time to spare, any interest in helping out maintaining this plugin?

**Comment by pmv** [comment]
I don't have any experience being a maintainer, and I'm not sure what all duties are involved.

If I had bigger plans for changes, I might be more inclined, but I expect this will be the only contribution I'll need to make to this plugin (if that makes a difference)...

**Comment by centic9** [comment]
Ok, understood, if you want to contribute just a small bit, there are smaller things that can help, e.g. triaging some of the open bugs on [JIRA](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+%28component+%3D+jacoco-plugin%29&tempMax=1000) or updating documentation or adding/improving some unit-tests...

**Pull request merged**
