### PR TITLE
Remove Joda Time dependency (JENKINS-43103).

### PR DESCRIPTION
**Pull request by veita**
This patch removes unnecessary dependency to Joda Time to fix JENKINS-43103.

https://issues.jenkins-ci.org/browse/JENKINS-43103

Note: The GitHub diffs show some weird whitespace-only differences. Appending `?w=1` to the diff URL solves this issue.

### CODE REVIEW

**Comment by jvasallo** [comment]
Thanks for this PR, fixed the same error I was seeing in reference to Joda-Time dependency missing.
👍 on using the STDLIB too. :)

**Comment by veita** [comment]
@jvasallo I don't have any experience if and when pull request are merged.

**Comment by centic9** [comment]
Can you re-do the PR without changing the newlines? This makes it hard to see the actual changes...

**Comment by centic9** [comment]
Thanks, merged now.

**Pull request merged**
