### PR TITLE
SpotBugs violations

### PR DESCRIPTION
**Pull request by jglick**
Observable when updating parent POM to 5.1 (when using a newer `jenkins.version`).

### CODE REVIEW

**Comment by MarkEWaite** [comment]
> Observable when updating parent POM to 5.1 (when using a newer `jenkins.version`).

Also observable on the master branch build with parent pom 4.88.

**Review by Vlatombe — APPROVED** [review]

**Comment by jglick** [comment]
Indeed, as of c75d76c9a94f3efb4e16e113143b5a77ae406704 @centic9. I would recommend using pull request flow to ensure regressions are not accidentally pushed to trunk. No approvals are needed; you can just configure automerge to run once the Jenkins CI check passes.

**Comment by jglick** [comment]
(Or you can simply configure Dependabot or Renovate for dependency updates like this.)

**Comment by jglick** [comment]
@centic9 https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Pull request merged**
