### PR TITLE
Jenkins 16580: Display more than only line coverage in graph

### PR DESCRIPTION
**Pull request by mheinzerling**
see https://issues.jenkins-ci.org/browse/JENKINS-16580

### CODE REVIEW

**Comment by mheinzerling** [comment]
Rebased.

**Comment by mheinzerling** [comment]
Rebased.

**Comment by centic9** [comment]
it seems you rebased onto changes done in PR66, however this makes it impossible to merge this onto master currently before PR66 is done, was this intentional?

**Comment by mheinzerling** [comment]
Kind of. This changes are nearly 2 years old and aren't commented or integrated yet. I need the workflow support in my local version, so it is at least useful for me.

**Comment by centic9** [comment]
Hi,

Are you interested in working on the jacoco-plugin directly? I don't know
much about Jenkins-plugin development and can only spend very little time
on it so it is a bit stale and could use some more man-power.

Dominik.

**Comment by mheinzerling** [comment]
Rebased on master

**Pull request merged**
