### PR TITLE
Improvements for pom.xml

### PR DESCRIPTION
**Pull request by darxriggs**
I suggest to review the commits individually.

The first commit fixes indentation & formatting of the XML and should not introduce any functional changes. The remaining commits cover other dedicated aspects.

### CODE REVIEW

**Comment by darxriggs** [comment]
@centic9 is there anything I can support you with regarding this pull request?

**Comment by centic9** [comment]
To be honest, I don't have much time to look after jacoco-plugin right now, I am mostly still following along because there is currently no-one else, would you be able to help maintaining it? It's not a huge codebase so would probably not require a big time-investment.

**Comment by darxriggs** [comment]
My goal is to improve many plugins. Therefore it's not feasible to step in as maintainer of this plugin.

**Comment by darxriggs** [comment]
I wanted to clean up the pom.xml first (via this pull request). And also try to reduce the plugin size (this would be another pull request).

**Comment by mheinzerling** [comment]
@centic9, I quickly checked it, and it seems to be save to merge. I'm just not sure if we have a general formatting recommendation for the pom. But as long as it is consistent, it's fine for me :)

**Comment by centic9** [comment]
Ok, thanks for the review!

**Pull request merged**
