### PR TITLE
Use ASM library plugin

### PR DESCRIPTION
**Pull request by basil**
https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#using-library-wrapper-plugins

### Testing done

Passing CI build: https://ci.jenkins.io/job/Plugins/job/jacoco-plugin/job/PR-278/10/

### CODE REVIEW

**Review by jonesbusy — APPROVED** [review]

**Review by centic9 — APPROVED** [review]

**Comment by basil** [comment]
Thanks! Looking forward to a release of this PR so that we can remove ASM from Jenkins core and allow users to upgrade ASM through the plugin system instead.

**Comment by NotMyFault** [comment]
@centic9 would you be so kind as to cut a release, please? That would allow us to move on, as outlined by basil.

**Comment by centic9** [comment]
Unfortunately uploading a new release broke again for me with an authentication problem during upload "401 Unauthorized", probably something changed somewhere in Jenkins-land, hard to dig into it every few months.... 

Probably time that one of you guys is added to releasers of this plugin as I cannot invest much time anyway.

**Comment by centic9** [comment]
Seems after another try it worked now.

**Pull request merged**
