### PR TITLE
Remove unnecessary dependency (plexus)

### PR DESCRIPTION
**Pull request by MRamonLeon**
Remove plexus from its new location

CC: @varyvol @rsandell @Wadeck

### CODE REVIEW

**Review by varyvol — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
Compiled before and after, the plexus-cipher was removed.

I have **not** tested the features of the plugin.

**Comment by MRamonLeon** [comment]
@centic9 , @ognjenb do you consider cutting a release to include this change? The java11 failure seems to be related with an infra issue:
```
[2020-09-15T06:25:16.695Z] EC2 (aws) - Windows 2019 (i-09c99229810b0235e) was marked offline: Connection was broken: java.io.EOFException

[2020-09-15T06:25:16.696Z] 	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2818)

[2020-09-15T06:25:16.696Z] 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3313)

[2020-09-15T06:25:16.696Z] 	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:907)

[2020-09-15T06:25:16.696Z] 	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:350)

[2020-09-15T06:25:16.696Z] 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)

[2020-09-15T06:25:16.696Z] 	at hudson.remoting.Command.readFrom(Command.java:142)

[2020-09-15T06:25:16.696Z] 	at hudson.remoting.Command.readFrom(Command.java:128)

[2020-09-15T06:25:16.696Z] 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)

[2020-09-15T06:25:16.696Z] 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)

[2020-09-15T06:25:16.696Z] Caused: java.io.IOException: Unexpected termination of the channel

[2020-09-15T06:25:16.696Z] 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
```

Thank you!

**Comment by MRamonLeon** [comment]
Closing and reopening to trigger a new build

**Comment by centic9** [comment]
released via jacoco-3.0.8

**Comment by MRamonLeon** [comment]
Thank you @centic9, very appreciated! I now can enjoy the weekend :beers:

**Pull request merged**
