### PR TITLE
JENKINS-43310 add source file inclusions and exclusions

### PR DESCRIPTION
**Pull request by spudmux**
The JaCoCo Plugin 2.2.0 release restricts source files copied to only include .java files. See [JENKINS-38604](https://issues.jenkins-ci.org/browse/JENKINS-38604) and commit [d771e0b](https://github.com/jenkinsci/jacoco-plugin/commit/d771e0b15933516917208f30dd54bad81b1c290d). Preventing other jvm language source files from being processed, such as .groovy, .gs .kt, etc. While coverage statistics are still available coverage is not shown graphically for the files. See the related bug [JENKINS-43310](https://issues.jenkins-ci.org/browse/JENKINS-43310).

This pull request adds configuration properties for source file inclusions and exclusions patterns. Allowing users to configure which files are copied from the sources directory.

It restructures the configuration UI to make it clear that,

- Existing inclusions and exclusions are applied to the .exec file.

- Classes cannot be configured with inclusions and exclusions. 

- Sources can be configured with inclusions exclusions.

Job Configuration

By default the source inclusions is set to `**/*.java` and the exclusions are blank.

### CODE REVIEW

**Comment by jweibel22** [comment]
I'm trying to generate coverage reports based on scala code and the source code is not showing up. Could we please get this pull request merged in?

**Comment by willyg** [comment]
Is there areason why this is not merged?

**Comment by ggrell** [comment]
Android Kotlin devs really need this fix in, any chance of getting it merged soon?

**Comment by centic9** [comment]
There was some discussion on the JIRA issue at https://issues.jenkins-ci.org/browse/JENKINS-43310 to improve the PR some more, see https://issues.jenkins-ci.org/browse/JENKINS-43310?focusedCommentId=296658&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-296658, would be good to get that done before we merge...

**Comment by henrik242** [comment]
Any progress on this?  It would be great to include kt & groovy files...

**Comment by centic9** [comment]
See my last comment, I hoped that this would be updated, but it seems this is not happening, so I will merge this as-is soon as it looks to be useful the way it is right now already.

**Comment by henrik242** [comment]
Thank you!

**Comment by henrik242** [comment]
@centic9 Looking forward to 3.0.2 ;)

**Comment by nedad** [comment]
When is this change available?

**Pull request merged**
